# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'laboratorio-final-diplomado'
    organization: 'm6mb3rtx'
    scannerMode: 'Other'
    projectKey: 'spring-boot-kubernetes'
    projectName: 'spring-boot-kubernetes'


- task: Maven@4
  displayName: 'Execute Maven goal'
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-Dmaven.test.failure.ignore=true'
    mavenOptions: '-Xmx3072m'
    mavenVersionOption: 'Default'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    codeCoverageToolOption: 'JaCoCo'
    testResultsFiles: '**/TEST-*.xml'
    goals: 'verify'


# Uncomment the next task to wait until SonarCloud processing has
# finished and to publish the result on the Pipeline build summary
- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'